// src/app/layout.tsx

import type { Metadata } from "next";
import localFont from "next/font/local";
import Navigation from '@/components/Navigation';
import "@/app/globals.css";

const defaultSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--default-sans",
  weight: "100 900",
});

const defaultMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--default-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "extrahop-nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body className={`${defaultSans.variable} ${defaultMono.variable} antialiased`}>
        <Navigation />
        <div className="ml-64 px-4 pt-4 sm:px-6 lg:px-8 font-[family-name:var(--default-sans)]">
          {children}
        </div>
      </body>
    </html>
  );
}
